# Generated by Django 2.0.5 on 2018-05-14 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargotype', models.CharField(max_length=12, verbose_name='Наименование груза')),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Отправитель/получатель', max_length=20, verbose_name='Компания')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_date', models.DateField(verbose_name='Дата разгрузки')),
                ('track_i', models.CharField(max_length=8, verbose_name='Номер грузовика')),
                ('trailer_i', models.CharField(max_length=8, verbose_name='Номер прицепа')),
                ('container_i', models.CharField(max_length=11, verbose_name='Номер контейнера')),
                ('upload', models.CharField(blank=True, choices=[('Нет', 'нет'), ('Да', 'да')], default='d', help_text='Снятие контейнера', max_length=3, verbose_name='Контейнер')),
                ('quantity_i', models.CharField(max_length=1, verbose_name='Количество')),
                ('cmr', models.CharField(max_length=12, verbose_name='CMR/TTH')),
                ('akt_i', models.CharField(max_length=5, verbose_name='Номер акта')),
                ('lot', models.CharField(max_length=19, verbose_name='Лот')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samsung.Cargo', verbose_name='Наименование груза')),
            ],
            options={
                'db_table': 'incoming',
            },
        ),
        migrations.CreateModel(
            name='Outcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcoming_date', models.DateField(verbose_name='Дата отгрузки')),
                ('track_o', models.CharField(max_length=8, verbose_name='Номер грузовика')),
                ('trailer_o', models.CharField(max_length=8, verbose_name='Номер прицепа')),
                ('akt_o', models.CharField(max_length=5, verbose_name='Номер акта')),
                ('quantity_o', models.CharField(max_length=1, verbose_name='Количество')),
                ('ttn', models.CharField(max_length=12, verbose_name='TTH')),
                ('comments', models.TextField(blank=True, max_length=50, null=True, verbose_name='Примечания')),
                ('akt_incoming', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samsung.Incoming')),
                ('recepient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samsung.Company', verbose_name='Получатель')),
            ],
            options={
                'db_table': 'outcoming',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=8, verbose_name='Ячейка')),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=12, verbose_name='Вид упаковки')),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.AddField(
            model_name='incoming',
            name='cell_position',
            field=models.ForeignKey(help_text='Место размещения на складе', null=True, on_delete=django.db.models.deletion.SET_NULL, to='samsung.Position', verbose_name='Ячейка'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samsung.Type', verbose_name='Вид упаковки'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samsung.Company', verbose_name='Отправитель'),
        ),
    ]
