# Generated by Django 2.0.5 on 2018-06-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samsung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='upload',
            field=models.CharField(choices=[('Нет', 'нет'), ('Да', 'да')], default='d', help_text='Снятие контейнера', max_length=3, verbose_name='Контейнер'),
        ),
        migrations.AlterField(
            model_name='outcoming',
            name='akt_incoming',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samsung.Incoming'),
        ),
    ]
