# Generated by Django 2.0.5 on 2018-06-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsung', '0002_auto_20180603_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='quantity_i',
            field=models.PositiveIntegerField(max_length=2, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='outcoming',
            name='quantity_o',
            field=models.PositiveIntegerField(max_length=2, verbose_name='Количество'),
        ),
    ]
