# Generated by Django 2.0.5 on 2018-07-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsung', '0003_auto_20180603_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='upload',
            field=models.CharField(choices=[('0', 'Нет'), ('1', 'Да')], default='d', help_text='Снятие контейнера', max_length=3, verbose_name='Контейнер'),
        ),
    ]
